Gapura/Models/Supplier.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gapura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.Products = new HashSet<Product>();
        }
    
        public int SupplierID { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Region { get; set; }
        public string Phone { get; set; }
        public string SupplierCode { get; set; }
        public int CategoryID { get; set; }
        public string CellPhone { get; set; }
        public string Npwp { get; set; }
        public Nullable<short> TermID { get; set; }
    
        public virtual ICollection<Product> Products { get; set; }
    }
}

Gapura/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Gapura.Models;

namespace Gapura.Controllers
{
    public class SuppliersController : Controller
    {
        private YSIDGAEntitiesConn dbConn = new YSIDGAEntitiesConn();

        //
        // GET: /Suppliers/

        public ActionResult Index()
        {
            return View(dbConn.Suppliers.ToList());
        }

        ///////////////-------------- Load Data by JQuery Fir 26102016 -----------------/////////////
        public ActionResult LoadData()
        {
            //using (YSIDGAEntitiesConn dc = new YSIDGAEntitiesConn())
            {
                // dc.Configuration.LazyLoadingEnabled = false; // if your table is relational, contain foreign key
                dbConn.Configuration.LazyLoadingEnabled = false;
                //var data = dbConn.Suppliers.OrderBy(s => s.CompanyName).ToList();             //default Way

                //var data = from s in dbConn.Suppliers                                             //Using LinQ
                //           join ca in dbConn.Categories on s.CategoryID equals ca.CategoryID
                //           orderby s.CompanyName
                //           select new { s.SupplierID, s.SupplierCode, ca.CategoryName, s.CompanyName, s.Address, s.City, s.Region, 
                //                        s.ContactName, s.Phone, s.CellPhone, s.Npwp, s.TermOfPayment };

                var data = dbConn.SPR_Suppliers().ToList();                                 //Using SP
                return Json(new { data = data }, JsonRequestBehavior.AllowGet);
            }
        }
        ///////////////-----------End Load Data by JQuery Fir 26102016 -----------------/////////////

        //
        // GET: /Suppliers/Details/5

        public ActionResult Details(int id = 0)
        {
            Supplier supplier = dbConn.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        //
        // GET: /Suppliers/Create

        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(dbConn.Categories, "CategoryID", "CategoryName");
            ViewBag.TermID = new SelectList(dbConn.TermOfPays, "TermID", "TermDays");
            return View();
        }

        //
        // POST: /Suppliers/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                dbConn.Suppliers.Add(supplier);
                dbConn.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(dbConn.Categories, "CategoryID", "CategoryName", supplier.CategoryID);
            ViewBag.TermID = new SelectList(dbConn.TermOfPays, "TermID", "TermDays", supplier.TermID);
            return View(supplier);
        }

        //
        // GET: /Suppliers/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Supplier supplier = dbConn.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }

            ViewBag.CategoryID = new SelectList(dbConn.Categories, "CategoryID", "CategoryName", supplier.CategoryID);
            ViewBag.TermID = new SelectList(dbConn.TermOfPays, "TermID", "TermDays", supplier.TermID);
            return View(supplier);
        }

        //
        // POST: /Suppliers/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                dbConn.Entry(supplier).State = EntityState.Modified;
                dbConn.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(dbConn.Categories, "CategoryID", "CategoryName", supplier.CategoryID);
            ViewBag.TermID = new SelectList(dbConn.TermOfPays, "TermID", "TermDays", supplier.TermID);
            return View(supplier);
        }

        //
        // GET: /Suppliers/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Supplier supplier = dbConn.Suppliers.Find(id);
            if (supplier == null)
            {
                return HttpNotFound();
            }
            return View(supplier);
        }

        //
        // POST: /Suppliers/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Supplier supplier = dbConn.Suppliers.Find(id);
            dbConn.Suppliers.Remove(supplier);
            dbConn.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            dbConn.Dispose();
            base.Dispose(disposing);
        }
    }
}

Gapura/Views/Suppliers/Create.cshtml
@model Gapura.Models.Supplier

@{
    ViewBag.Title = "Create Supplier";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title>
            <h2><i class="icon-pencil"></i><span
                class="break"></span>Create Supplier</h2>
            <div class="box-icon">
                @*<a href="~/Products/Index" class="btn-setting"><i class="halflings-icon wrench"></i></a>*@
                <a href="@Url.Action("Index", "Suppliers")" 
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Create", "Suppliers", FormMethod.Post, new
        {
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    <div class="editor-label">
                        @Html.Label("SupplierCode", "Supplier Code", new { @class = "control-label" })

                        @Html.EditorFor(model => model.SupplierCode)
                        @Html.ValidationMessageFor(model => model.SupplierCode)
                    </div>

                    <div class="editor-label">
                        @Html.Label("CategoryID", "Category", new { @class = "control-label" })

                        @Html.DropDownList("CategoryID", String.Empty)
                        @Html.ValidationMessageFor(model => model.CategoryID)
                    </div>

                    <div class="editor-label">
                        @Html.Label("CompanyName", "Company Name", new { @class = "control-label" })

                        @Html.EditorFor(model => model.CompanyName)
                        @Html.ValidationMessageFor(model => model.CompanyName)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Address", "Address", new { @class = "control-label" })

                        @Html.TextAreaFor(model => model.Address)
                        @Html.ValidationMessageFor(model => model.Address)
                    </div>

                    <div class="editor-label">
                        @Html.Label("City", "City", new { @class = "control-label" })

                        @Html.EditorFor(model => model.City)
                        @Html.ValidationMessageFor(model => model.City)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Region", "Region", new { @class = "control-label" })

                        @Html.EditorFor(model => model.Region)
                        @Html.ValidationMessageFor(model => model.Region)
                    </div>

                    <div class="editor-label">
                        @Html.Label("ContactName", "Contact Name", new { @class = "control-label" })

                        @Html.EditorFor(model => model.ContactName)
                        @Html.ValidationMessageFor(model => model.ContactName)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Phone", "Phone", new { @class = "control-label" })

                        @Html.EditorFor(model => model.Phone)
                        @Html.ValidationMessageFor(model => model.Phone)
                    </div>

                    <div class="editor-label">
                        @Html.Label("CellPhone", "CellPhone", new { @class = "control-label" })

                        @Html.EditorFor(model => model.CellPhone)
                        @Html.ValidationMessageFor(model => model.CellPhone)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Npwp", "NPWP", new { @class = "control-label" })

                        @Html.EditorFor(model => model.Npwp)
                        @Html.ValidationMessageFor(model => model.Npwp)
                    </div>

                    <div class="editor-label">
                        @Html.Label("TermOfPayment", "Term Of Payment", new { @class = "control-label" })

                        @Html.DropDownList("TermID", String.Empty)
                        @Html.ValidationMessageFor(model => model.TermID)
                    </div>

                    <div class="form-actions">
                        <a class="btn btn-success" href="#" onclick="$('form').submit();">Save</a>
                        <input type="reset" value="Reset" class="btn" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    div.editor-label {
        margin-bottom: 14px !important;
    }
</style>

Gapura/Views/Suppliers/Delete.cshtml
@model Gapura.Models.Supplier

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CompanyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CompanyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactTitle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactTitle)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Region)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Region)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostalCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostalCode)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fax)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fax)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HomePage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HomePage)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Gapura/Views/Suppliers/Details.cshtml
@model Gapura.Models.Supplier

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Supplier</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.CompanyName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CompanyName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ContactTitle)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ContactTitle)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.City)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.City)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Region)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Region)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PostalCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PostalCode)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Country)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Country)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Phone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Phone)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Fax)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Fax)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.HomePage)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HomePage)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.SupplierID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Gapura/Views/Suppliers/Edit.cshtml
@model Gapura.Models.Supplier

@{
    ViewBag.Title = "Edit Supplier";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title>
            <h2><i class="icon-edit"></i><span
                class="break"></span>Edit Supplier</h2>
            <div class="box-icon">
                @*<a href="~/Products/Index" class="btn-setting"><i class="halflings-icon wrench"></i></a>*@
                <a href="@Url.Action("Index", "Suppliers")" 
                    title="Return to Index List" >
                    <i class="halflings-icon chevron-up"></i><span class="hidden-tablet"></span>
                </a>
                <a href="~/Home/Index" class="btn-close"
                    title="Return to Homepage">
                    <i class="halflings-icon remove"></i>
                </a>
            </div>
        </div>
        <div class="box-content">

            @using (Html.BeginForm("Edit", "Suppliers", FormMethod.Post, new
        {
            @class = "form-horizontal"
        }))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>
                    <legend></legend>

                    @Html.HiddenFor(Model => Model.SupplierID)

                    <div class="editor-label">
                        @Html.Label("SupplierCode", "Supplier Code", new { @class = "control-label" })

                        @Html.EditorFor(model => model.SupplierCode)
                        @Html.ValidationMessageFor(model => model.SupplierCode)
                    </div>

                    <div class="editor-label">
                        @Html.Label("CategoryID", "Category", new { @class = "control-label" })

                        @Html.DropDownList("CategoryID", String.Empty)
                        @Html.ValidationMessageFor(model => model.CategoryID)
                    </div>

                    <div class="editor-label">
                        @Html.Label("CompanyName", "Company Name", new { @class = "control-label" })

                        @Html.EditorFor(model => model.CompanyName)
                        @Html.ValidationMessageFor(model => model.CompanyName)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Address", "Address", new { @class = "control-label" })

                        @*@Html.TextArea("Address", String.Empty, new { @rows = "5", @class = "span6 typeahead" })*@
                        @Html.TextAreaFor(model => model.Address)
                        @Html.ValidationMessageFor(model => model.Address)
                    </div>

                    <div class="editor-label">
                        @Html.Label("City", "City", new { @class = "control-label" })

                        @Html.EditorFor(model => model.City)
                        @Html.ValidationMessageFor(model => model.City)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Region", "Region", new { @class = "control-label" })

                        @Html.EditorFor(model => model.Region)
                        @Html.ValidationMessageFor(model => model.Region)
                    </div>

                    <div class="editor-label">
                        @Html.Label("ContactName", "Contact Name", new { @class = "control-label" })

                        @Html.EditorFor(model => model.ContactName)
                        @Html.ValidationMessageFor(model => model.ContactName)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Phone", "Phone", new { @class = "control-label" })

                        @Html.EditorFor(model => model.Phone)
                        @Html.ValidationMessageFor(model => model.Phone)
                    </div>

                    <div class="editor-label">
                        @Html.Label("CellPhone", "CellPhone", new { @class = "control-label" })

                        @Html.EditorFor(model => model.CellPhone)
                        @Html.ValidationMessageFor(model => model.CellPhone)
                    </div>

                    <div class="editor-label">
                        @Html.Label("Npwp", "NPWP", new { @class = "control-label" })

                        @Html.EditorFor(model => model.Npwp)
                        @Html.ValidationMessageFor(model => model.Npwp)
                    </div>

                    <div class="editor-label">
                        @Html.Label("TermDays", "Term Of Payment", new { @class = "control-label" })

                        @Html.DropDownList("TermID", String.Empty)
                        @Html.ValidationMessageFor(model => model.TermID)
                    </div>

                    <div class="form-actions">
                        <a class="btn btn-success" href="#" onclick="$('form').submit();">Save</a>
                        <input type="reset" value="Reset" class="btn" />
                        <a href="@Url.Action("Index")" class="btn btn-info">Cancel</a>
                        <a href="@Url.Action("Delete", new { id = @Html.DisplayFor(model => model.SupplierID) })" class="btn btn-danger">Delete</a>
                    </div>
                </fieldset>
            }
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<style>
    div.editor-label {
        margin-bottom: 14px !important;
    }
</style>

Gapura/Views/Suppliers/Index.cshtml
@model IEnumerable<Gapura.Models.Supplier>

@{
    ViewBag.Title = "Supplier List ";
}

<div class="row-fluid sortable">
    <div class="box span12" style="margin-left: 0px">
        <div class="box-header" data-original-title>
            <h2><i class="icon-table"></i><span
                class="break"></span>Master Data Supplier</h2>
            <div class="box-icon">
                <a href="@Url.Action("Create", "Suppliers")">
                    <i class="halflings-icon plus"></i><span class="hidden-tablet"></span>
                    Add New Supplier
                </a>
            </div>
        </div>
        <div class="box-content">
            <div style="width: inherit; margin-left: 24px;">
                <table id="myTable" class="compact stripe hover order-column responsive" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.SupplierCode)
                            </th>
                            <th>Category Name
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CompanyName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Address)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.City)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Region)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ContactName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Phone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CellPhone)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Npwp)
                            </th>
                            <th>Terms Day
                            </th>
                            <th>-
                            </th>
                        </tr>
                    </thead>
                </table>
            </div>
            @section Scripts{
                @Scripts.Render("~/bundles/dataTables")
                <script src="~/Scripts/Suppliers/IndexSuppliers.js"></script>
            }
        </div>
    </div>
</div>

<style>
    th {
        background-color: #cdcdcd !important;
        border: dotted 1px;
    }
    td {
        border: dotted 1px;
    }
</style>

@Styles.Render("~/Content/dataTables")